### ISSUE TITLE
README example 1 output 

### ISSUE THREAD

**Issue by unaschneck** [gabbyprovan/con2020#15]
Hi, I am trying to run the first example in your readme but I am not getting `Bxyz=[15.57977074, 36.88229249, 63.02051163] nT` and `Brtp =[63.32354453 ,31.15790459], [-21.01051861 , -6.867]`

Here is the script I am running which prints `Bcart = [[240.52882122 405.78127896  71.88211533]]` and `Bpol = [[  64.63451393  -18.60838773   -4.42351731]
 [ 834.60398012 1260.51076529 -359.26051095]]`: 
```
import con2020

#initialize a model object with default parameters
def_model = con2020.Model()

#initialize a model which uses spherical polar coordinates for input and output
sph_model = con2020.Model(CartesianIn=False,CartesianOut=False)

#initialize a model with custom parameters (longhand)
cust_model0 = con2020.Model(mu_i_div2__current_parameter_nT=150.0,
                           	r0__inner_rj=9.5,
                           	d__cs_half_thickness_rj=3.1)

#equivalently, a custom parameter model (shorthand)
cust_model1 = con2020.Model(mu_i=150.0,r0=9.5,d=3.1)

x = 5.0
y = 10.0
z = 6.0
Bcart = def_model.Field(x,y,z)
print(Bcart)

r = np.array([10.0,20.0])					#radial distance in Rj
theta = np.array([30.0,35.0])*np.pi/180.0	#colatitude in radians 
phi = np.array([90.0,95.0])*np.pi/180.0	#east longitude in radians
Bpol = sph_model.Field(r,theta,phi)
print(Bpol)

```

**Comment by gabbyprovan** [comment]
Hi, Thank you so much for reaching out.  It has taken us ages to find the bug  - we are very grateful that you pointed it out.  Basically, there was an error with the hyperbolic tangents in the LargeRhoApproxEdwards definition in Analytic.py.  I have fixed it now.  Please try again and please let me know if it works.  Thanks again, Gabby

**Comment by unaschneck** [comment]
Thank you! I am getting much closer now. For the following I get ```Bcart = [[15.58367964 36.8963783  63.04540543]]```, which is within an order of magnitude of the magnetic field results listed in the example but still seems a little off in beyond the hundreds place compared to ```Bxyz=[15.57977074, 36.88229249, 63.02051163]```. 

```
import numpy as np

import con2020

#initialize a model object with default parameters
def_model = con2020.Model()

#initialize a model which uses spherical polar coordinates for input and output
sph_model = con2020.Model(CartesianIn=False,CartesianOut=False)

#initialize a model with custom parameters (longhand)
cust_model0 = con2020.Model(mu_i_div2__current_parameter_nT=150.0,
                           	r0__inner_rj=9.5,
                           	d__cs_half_thickness_rj=3.1)

#equivalently, a custom parameter model (shorthand)
cust_model1 = con2020.Model(mu_i=150.0,r0=9.5,d=3.1)
#Example 1: the model at a single Cartesian position (all in Rj)
x = 5.0
y = 10.0
z = 6.0
Bcart = def_model.Field(x,y,z)
print(F"Bcart = {Bcart}")
```

**Comment by gabbyprovan** [comment]
Hi, Thank you for checking.  Actually, we had forgotten to update the readme files after a small code update  -involving merging the results from the small and the large rho approximations using hyperbolic tangents - so the values you calculated are correct.  I have updatedt the webpage accordingly
